language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
- mvn clean install sonar:sonar
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.organization=ben12-github
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.branch.name=${TRAVIS_BRANCH}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
